### ISSUE TITLE
Error after trying to add an image

### ISSUE THREAD

**Issue by ghost** [nttcom/redmine_objectstorage#1]
Get the following error after trying to add an image in issues. 

```
Excon::Error::Socket (getaddrinfo: Name or service not known (SocketError)):
  plugins/redmine_objectstorage/lib/redmine_objectstorage/attachment_patch.rb:50:in `objectstorage_bucket'
  plugins/redmine_objectstorage/lib/redmine_objectstorage/attachment_patch.rb:87:in `save_to_objectstorage'
  app/controllers/attachments_controller.rb:97:in `upload'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Any ideas?

**Comment by vinznsk** [comment]
Yep, I have the same problem
