### ISSUE TITLE
 cannot load such file -- net/ssh (LoadError)

### ISSUE THREAD

**Issue by vinznsk** [nttcom/redmine_objectstorage#2]
Hello,

I'm trying to install this plugin on Redmine 3.4, but I get an error:

/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- net/ssh (LoadError)
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /var/lib/gems/2.1.0/gems/fog-1.29.0/lib/fog/joyent/compute.rb:3:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /var/lib/gems/2.1.0/gems/fog-1.29.0/lib/fog/joyent.rb:1:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from /var/lib/gems/2.1.0/gems/fog-1.29.0/lib/fog.rb:41:in `<top (required)>'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `require'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `block (2 levels) in require'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `each'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `block in require'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `each'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `require'
        from /var/lib/gems/2.1.0/gems/bundler-1.16.0.pre.3/lib/bundler.rb:114:in `require'
        from /usr/local/share/redmine/config/application.rb:5:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/redmine/config/environment.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/redmine/config.ru:3:in `block in <main>'
        from /var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
        from /usr/local/share/redmine/config.ru:1:in `new'
        from /usr/local/share/redmine/config.ru:1:in `<main>'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:42:in `for'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:74:in `start'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        from /var/lib/gems/2.1.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>

**Comment by sindhu-shree-1** [comment]
I'm getting the same error. 
I was getting an `RbNaCl::LengthError` so I upgraded `net-ssh` to v5.0; after which I started getting this: `require': cannot load such file -- net/ssh (LoadError)`

I don't think this is related to fog's version because I have this in my gemset: `fog-core-1.45.0`
